FROM nytimes/blender:3.2-cpu-ubuntu18.04

WORKDIR /code

COPY . /code

RUN $BLENDERPIP install --no-cache-dir --upgrade -r /code/requirements.txt

ENV TMP_DIRECTORY "/tmp/minecraft-blender-render-api"

EXPOSE $PORT

CMD uvicorn main:app --host 0.0.0.0 --port $PORT --proxy-headers
